version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aug15-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-byc8vm6t806u"
s3_prefix = "aug15-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "QuickSightUserName=\"Admin/tarporn-Isengard\" InventoryBucketName=\"eol-dashboard-example\""
image_repositories = []
